### ISSUE TITLE
Rodan doesn't get XP

### ISSUE THREAD

**Issue by gojigodzuki2014-Orca** [vret001/KU_Issues#13]
Hi, I'm Orca from the PG server and gojigodzuki2014 on Roblox. I would like to report a bug, that being that whenever I attack as Titanus Rodan, I don't get any XP. No matter how much I attack, I don't get any at all. I don't know if it's just a me thing, but if it could be fixed it would help a lot. Thank You

**Comment by vret001** [comment]
This was a hitbox issue and should now be solved
